version: "3"

services:
  keylog:
    build: .
    container_name: myapp_c
    command: sh -c "uvicorn keylogging:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
